min_version = '2026.1.5'

[tools]
rust = "1.93"
rust-analyzer = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"http:clitest" = { version = "latest", url = "https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest" }
jq = "latest"

[task_config]
includes = ["script"]
