[toolchain]
channel = "stable"
components = ["cargo", "rust-std", "rustc", "rustfmt", "clippy"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "riscv64gc-unknown-linux-musl"
]
